name: teach_savvy
description: Teach Savvy App
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  get_it: ^8.0.0
  http: ^1.2.2
  http_interceptor: ^2.0.0
  hydrated_bloc: ^9.1.5
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  jiffy: ^6.3.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  upgrader: ^11.3.0
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
